### ISSUE TITLE
Maximum Subarray

### ISSUE THREAD

**Issue by dumbbutgenius** [HacktoberfestSIT/Problem-Solving#17]
https://leetcode.com/problems/maximum-subarray/

**Comment by shivanshi-s** [comment]
Hello, can I work on this as a part of hacktoberfest?

**Comment by deepdhar** [comment]
in which language do you want to give the solution?

**Comment by shivanshi-s** [comment]
I will be doing it in c++ @deepdhar

**Comment by deepdhar** [comment]
@shivanshi-s assigned the issue for C++ solution

**Comment by aman-raza** [comment]
Please update contributors.md @shivanshi-s

**Comment by shivanshi-s** [comment]
I did update it with the solution @aman-raza

**Comment by aman-raza** [comment]
your code is showing a few conflicts in it
it will get merged after the conflict get resolved

**Comment by Tanisha-creator** [comment]
I want to work on this solution using C++
