### ISSUE TITLE
Shuffle the array

### ISSUE THREAD

**Issue by deepdhar** [HacktoberfestSIT/Problem-Solving#22]
Arrays -> 4. Shuffle the array ->
problem link: https://leetcode.com/problems/shuffle-the-array/
use any programming language of your choice

**Comment by Gourav-78** [comment]
I want to work on this issue..I can provide the solution in C/C++

**Comment by ishar19** [comment]
Here is my submission link with C++ faster than 100% of solutions. https://leetcode.com/submissions/detail/564566943/


@Gourav8152-ai @deepdhar please review.

**Comment by surbhi2408** [comment]
I want to work on this issue.

**Comment by Gourav8152-ai** [comment]
> I want to work on this issue.

Mention the language in which you want to work.

**Comment by surbhi2408** [comment]
> > I want to work on this issue.
> 
> Mention the language in which you want to work.

I will work on C++.
