### ISSUE TITLE
Number of Good Pairs

### ISSUE THREAD

**Issue by deepdhar** [HacktoberfestSIT/Problem-Solving#23]
Maths ->

problem link: https://leetcode.com/problems/number-of-good-pairs/

**Comment by Gourav-78** [comment]
I want to work on this issue..I can provide the solution in C/C++

**Comment by deepdhar** [comment]
> I want to work on this issue..I can provide the solution in C/C++

Assigned issue for C/C++ solution

**Comment by Samhitha-Jasti** [comment]
I would like to work on this issue using Java
