### ISSUE TITLE
Quick Sort

### ISSUE THREAD

**Issue by deepdhar** [HacktoberfestSIT/Problem-Solving#8]
Add a solution program for quick sort in any programming language

**Comment by Anoushka-Ghosh** [comment]
I want to work on this issue

**Comment by Gourav-78** [comment]
I want to work on this issue..I can provide the solution in C/C++

**Comment by dcod3r** [comment]
I want to work on this issue

**Comment by deepdhar** [comment]
@Anoushka-Ghosh @dcod3r  in which language do you want to give the solution?

**Comment by Anoushka-Ghosh** [comment]
I want to work on this issue in C

**Comment by dcod3r** [comment]
I want to work on this issue in C

**Comment by dcod3r** [comment]
I want to work on this issue in C

**Comment by deepdhar** [comment]
@dcod3r assigned the issue for C solution
@Gourav-78 assigned the issue for CPP solution

**Comment by LikhithaTadikonda** [comment]
I want to contribute too.
